export const GENRE_MAP: Record<string, number> = {
    // English
    "Action": 1,
    "Adventure": 2,
    "Cars": 3,
    "Comedy": 4,
    "Avangarde": 5,
    "Avant Garde": 5, // Variant
    "Demons": 6,
    "Mystery": 7,
    "Drama": 8,
    "Ecchi": 9,
    "Fantasy": 10,
    "Game": 11,
    "Hentai": 12,
    "Historical": 13,
    "Horror": 14,
    "Kids": 15,
    "Martial Arts": 17,
    "Mecha": 18,
    "Music": 19,
    "Parody": 20,
    "Samurai": 21,
    "Romance": 22,
    "School": 23,
    "Sci-Fi": 24,
    "Shoujo": 25,
    "Shoujo Ai": 26,
    "Shounen": 27,
    "Shounen Ai": 28,
    "Space": 29,
    "Sports": 30,
    "Super Power": 31,
    "Vampire": 32,
    "Yaoi": 33,
    "Yuri": 34,
    "Harem": 35,
    "Slice of Life": 36,
    "Supernatural": 37,
    "Military": 38,
    "Police": 39,
    "Psychological": 40,
    "Thriller": 41,
    "Seinen": 42,
    "Josei": 43,
    "Doujinshi": 44,
    "Gender Bender": 45,
    "Suspense": 41,
    "Award Winning": 46,
    "Gourmet": 47,
    "Workplace": 48,
    "Erotica": 49,
    "Adult Cast": 50,
    "Anthropomorphic": 51,
    "CGDCT": 52,
    "Childcare": 53,
    "Combat Sports": 54,
    "Delinquents": 55,
    "Educational": 56,
    "Gag Humor": 57,
    "Gore": 58,
    "High Stakes Game": 59,
    "Idols (Female)": 60,
    "Idols (Male)": 61,
    "Isekai": 62,
    "Iyashikei": 63,
    "Love Polygon": 64,
    "Magical Sex Shift": 65,
    "Mahou Shoujo": 66,
    "Medical": 67,
    "Organized Crime": 68,
    "Otaku Culture": 69,
    "Performing Arts": 70,
    "Pets": 71,
    "Racing": 72,
    "Reincarnation": 73,
    "Reverse Harem": 74,
    "Romantic Subtext": 75,
    "Showbiz": 76,
    "Survival": 77,
    "Team Sports": 78,
    "Time Travel": 79,
    "Video Game": 80,
    "Visual Arts": 81,
    "Crossdressing": 81,

    // Portuguese Translations and Common Variations
    "Ação": 1,
    "Aventura": 2,
    "Carros": 3,
    "Comédia": 4,
    "Comedia": 4,
    "Vanguarda": 5,
    "Demônios": 6,
    "Demonios": 6,
    "Mistério": 7,
    "Misterio": 7,
    // Drama is same
    // Ecchi is same
    "Fantasia": 10,
    "Jogos": 11,
    // Hentai is same
    "Histórico": 13,
    "Historico": 13,
    "Horror (Terror)": 14,
    "Terror": 14,
    "Infantil": 15,
    "Artes Marciais": 17,
    // Mecha is same
    "Música": 19,
    "Musica": 19,
    "Paródia": 20,
    "Parodia": 20,
    // Samurai is same
    // Romance is same
    "Vida Escolar": 23,
    "Ficção Científica": 24,
    "Ficção": 24,
    // Sci-Fi is same
    // Shoujo/Shounen usually kept as is, but adding visual variations just in case
    "Shoujo-ai": 26,
    "Shounen-ai": 28,
    "Espaço": 29,
    "Esporte": 30,
    "Esportes": 30,
    "Super Poderes": 31,
    "Super-heróis": 31,
    "Vampiro": 32,
    "Vampiros": 32,
    // Yaoi/Yuri/Harem same
    "Vida Cotidiana": 36,
    "Slice-of-Life": 36,
    "Sobrenatural": 37,
    "Militar": 38,
    "Policial": 39,
    "Psicológico": 40,
    "Psicologico": 40,
    // Suspense is same
    // Seinen/Josei same
    "Gênero Trocado": 45,
    "Premiado": 46,
    // Gourmet same
    "Local de Trabalho": 48,
    "Erótico": 49,
    "Elenco Adulto": 50,
    "Antropomórfico": 51,
    // CGDCT same
    "Cuidados Infantis": 53,
    "Esportes de Combate": 54,
    "Delinquentes": 55,
    "Educacional": 56,
    "Humor Nonsense": 57,
    // Gore same
    "Jogos de Alto Risco": 59,
    "Idols (Feminino)": 60,
    "Idols (Masculino)": 61,
    // Isekai same
    // Iyashikei same
    "Triângulo Amoroso": 64,
    "Mudança de Sexo Mágica": 65,
    "Garotas Mágicas": 66,
    // Mahou Shoujo is same
    "Médico": 67,
    "Medico": 67,
    "Crime Organizado": 68,
    "Cultura Otaku": 69,
    "Artes Performáticas": 70,
    // Pets same
    "Corrida": 72,
    "Reencarnação": 73,
    "Reencarnacao": 73,
    "Harem Inverso": 74,
    "Subtexto Romântico": 75,
    "Show business": 76,
    "Sobrevivência": 77,
    "Sobrevivencia": 77,
    "Esportes de Time": 78,
    "Viagem no Tempo": 79,
    "Video Games": 80,
    "Artes Visuais": 81,
    // Crossdressing is same
};
